# Generated by Django on...
from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('BigHouseWeb', 'UserProfile')
    
    for user in User.objects.all():
        # Check if profile already exists
        if not UserProfile.objects.filter(user=user).exists():
            UserProfile.objects.create(user=user)

class Migration(migrations.Migration):
    dependencies = [
        # Your latest migration here
        ('BigHouseWeb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
