# Generated by Django 5.2.5 on 2025-09-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigHouseWeb', '0003_remove_building_manager_building_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
