# Generated by Django 5.2.5 on 2025-09-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigHouseWeb', '0006_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics/images'),
        ),
    ]
